Submission ran but did not finish its execution due to the errors below. 
This does not mean the program did not execute however, it may or may not have produced some files or none: 

 Traceback (most recent call last):
  File "***Removed due to privacy***/decrypt_p86963sp/./decrypt_p86963sp.py", line 11, in <module>
    inputF = open(inputFile, "r")
IsADirectoryError: [Errno 21] Is a directory: './test_files_encrypt'

No files were created within the results folder. (This does not mean files were not created elsewhere)
