Submission ran but did not finish its execution due to the errors below. 
This does not mean the program did not execute however, it may or may not have produced some files or none: 

 Traceback (most recent call last):
  File "***Removed due to privacy***/spellcheck_e86238yj/./spellcheck_e86238yj.py", line 14, in <module>
    os.mkdir(args.output_path)
FileExistsError: [Errno 17] File exists: './results_spell'

No files were created within the results folder. (This does not mean files were not created elsewhere)
