Submission ran but did not finish its execution due to the errors below. 
This does not mean the program did not execute however, it may or may not have produced some files or none: 

 Traceback (most recent call last):
  File "***Removed due to privacy***/rugby_v30867dh/./rugby_v30867dh.py", line 47, in <module>
    main()
  File "***Removed due to privacy***/rugby_v30867dh/./rugby_v30867dh.py", line 43, in main
    score(v)
NameError: name 'v' is not defined

No files were created within the results folder. (This does not mean files were not created elsewhere)
