Submission ran but did not finish its execution due to the errors below. 
This does not mean the program did not execute however, it may or may not have produced some files or none: 

 Traceback (most recent call last):
  File "***Removed due to privacy***/rugby_n07219hm/./rugby_n07219hm.py", line 89, in <module>
    write_to_output_file(output_file_path,calculate_score(read_input_file(input_folder_path + str(file_list[i]))))
  File "***Removed due to privacy***/rugby_n07219hm/./rugby_n07219hm.py", line 15, in read_input_file
    input_file = open(file,"r")
FileNotFoundError: [Errno 2] No such file or directory: './test_files_rugbytest_file1.txt'

No files were created within the results folder. (This does not mean files were not created elsewhere)
