Submission ran but did not finish its execution due to the errors below. 
This does not mean the program did not execute however, it may or may not have produced some files or none: 

 Traceback (most recent call last):
  File "***Removed due to privacy***/spellcheck_y48052as/./spellcheck_y48052as.py", line 146, in <module>
    spell_bee(args.x, file, args.z)	
  File "***Removed due to privacy***/spellcheck_y48052as/./spellcheck_y48052as.py", line 15, in spell_bee
    file1 = open(file_111)
FileNotFoundError: [Errno 2] No such file or directory: './test_files_spelltest_file1.txt'

No files were created within the results folder. (This does not mean files were not created elsewhere)
